# Generated by Django 6.0.3 on 2026-04-13 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_custom_auth', '0003_customuser_avatar_url_customuser_bio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waitlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
