# Generated by Django 6.0.3 on 2026-04-05 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='hype_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wallet',
            name='support_points',
            field=models.IntegerField(default=0),
        ),
    ]
