# Generated by Django 6.0.3 on 2026-04-06 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('subscription', 'Subscription Payment'), ('stream_payout', 'Stream Payout'), ('purchase_support', 'Support Point Purchase'), ('purchase_hype', 'Hype Point Purchase'), ('hype_spend', 'Hype Point Spending'), ('refund', 'Refund')], max_length=20),
        ),
    ]
