# Generated by Django 6.0.3 on 2026-03-20 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listener', '0002_song_total_play_count_songplay'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlySongStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('total_plays', models.BigIntegerField(default=0)),
                ('unique_listeners', models.BigIntegerField(default=0)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_stats', to='listener.song')),
            ],
        ),
        migrations.DeleteModel(
            name='SongPlay',
        ),
        migrations.AddIndex(
            model_name='monthlysongstats',
            index=models.Index(fields=['year', 'month'], name='listener_mo_year_58c21d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='monthlysongstats',
            unique_together={('song', 'year', 'month')},
        ),
    ]
