# Generated by Django 6.0.3 on 2026-03-29 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '__first__'),
        ('listener', '0003_monthlysongstats_delete_songplay_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterUniqueTogether(
                    name='monthlysongstats',
                    unique_together=None,
                ),
                migrations.RemoveIndex(
                    model_name='monthlysongstats',
                    name='listener_mo_year_58c21d_idx',
                ),
                migrations.RemoveField(
                    model_name='song',
                    name='uploaded_by',
                ),
                migrations.DeleteModel(
                    name='MonthlySongStats',
                ),
                migrations.DeleteModel(
                    name='Song',
                ),
            ],
            database_operations=[]
        ),
        migrations.AlterField(
            model_name='userlibrary',
            name='saved_songs',
            field=models.ManyToManyField(related_name='saved_by_users', to='creator.song'),
        ),
    ]
