# Generated by Django 6.0.3 on 2026-03-29 22:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listener', '0003_monthlysongstats_delete_songplay_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Song',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('title', models.CharField(max_length=255)),
                        ('artist', models.CharField(max_length=255)),
                        ('genre', models.CharField(choices=[('afrobeats', 'Afrobeats'), ('hiphop', 'Hip-Hop'), ('rnb', 'R&B'), ('gospel', 'Gospel'), ('pop', 'Pop'), ('electronic', 'Electronic'), ('rock', 'Rock'), ('jazz', 'Jazz'), ('other', 'Other')], default='other', max_length=100)),
                        ('tags', models.CharField(blank=True, default='', max_length=500)),
                        ('duration', models.CharField(blank=True, default='0:00', max_length=10)),
                        ('cover_image_url', models.URLField(blank=True, max_length=500, null=True)),
                        ('audio_file_url', models.URLField(blank=True, max_length=500, null=True)),
                        ('is_featured', models.BooleanField(default=False)),
                        ('is_trending', models.BooleanField(default=False)),
                        ('total_play_count', models.PositiveIntegerField(default=0)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_songs', to=settings.AUTH_USER_MODEL)),
                    ],
                ),
                migrations.CreateModel(
                    name='MonthlySongStats',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('year', models.IntegerField()),
                        ('month', models.IntegerField()),
                        ('total_plays', models.BigIntegerField(default=0)),
                        ('unique_listeners', models.BigIntegerField(default=0)),
                        ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_stats', to='creator.song')),
                    ],
                    options={
                        'indexes': [models.Index(fields=['year', 'month'], name='creator_mon_year_044340_idx')],
                        'unique_together': {('song', 'year', 'month')},
                    },
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE listener_song RENAME TO creator_song;",
                    reverse_sql="ALTER TABLE creator_song RENAME TO listener_song;",
                ),
                migrations.RunSQL(
                    sql="ALTER TABLE listener_monthlysongstats RENAME TO creator_monthlysongstats;",
                    reverse_sql="ALTER TABLE creator_monthlysongstats RENAME TO listener_monthlysongstats;",
                ),
            ]
        ),
    ]
