# Generated by Django 6.0.3 on 2026-03-29 22:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('entertainment', 'Entertainment'), ('education', 'Education'), ('news', 'News'), ('technology', 'Technology'), ('music', 'Music'), ('other', 'Other')], default='other', max_length=100)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('unlisted', 'Unlisted')], default='public', max_length=50)),
                ('cover_image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('audio_file_url', models.URLField(blank=True, max_length=500, null=True)),
                ('duration', models.CharField(blank=True, default='0:00', max_length=10)),
                ('total_play_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_podcasts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
