# Generated by Django 6.0.3 on 2026-03-31 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0004_podcastcomment_podcastlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='hype_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
