# Generated by Django 6.0.3 on 2026-04-02 18:50

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0006_songlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True),
        ),
    ]
