# Generated by Django 6.0.3 on 2026-04-03 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0007_song_embedding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='embedding',
        ),
    ]
