# Generated by Django 6.0.3 on 2026-04-03 11:42

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0009_song_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=3072, null=True),
        ),
    ]
